Repository mozilla/addons-linter, pull requests merged in 2018-03, with the labels that each got.

#1822 Async/await refactoring tests/test.linter.js
  src/const.js
  src/linter.js
  tests/test.linter.js
Labels: state: in progress

#1805 Async/await refactoring for scanners tests
  src/scanners/javascript.js
  tests/scanners/test.base.js
  tests/scanners/test.binary.js
  tests/scanners/test.css.js
  tests/scanners/test.filename.js
  tests/scanners/test.html.js
  tests/scanners/test.javascript.js
  tests/scanners/test.json.js
  tests/scanners/test.langpack.js
Labels: state: pull request ready

#1785 Fixed Jed gettext function
  .eslintignore
  package.json
  src/const.js
  src/linter.js
  src/messages/css.js
  src/messages/fluent.js
  src/messages/html.js
  src/messages/javascript.js
  src/messages/json.js
  src/messages/layout.js
  src/messages/locale-messagesjson.js
  src/messages/manifestjson.js
  src/scanners/javascript.js
  src/utils.js
  tests/fixtures/de.js
  tests/fixtures/fr.js
  tests/fixtures/ja.js
  tests/test.messages.js
  tests/test.utils.js
Labels: state: in progress

#1934 Import Firefox 60 schemas again
  src/schema/imported/devtools.json
  src/schema/imported/dns.json
  src/schema/imported/downloads.json
  src/schema/imported/index.js
  src/schema/imported/manifest.json
  src/schema/imported/proxy.json
  src/schema/imported/theme.json
  src/schema/imported/top_sites.json
Labels: component: schema, priority: blocks release
